#
####################################
#  !!! SQL_MODE=NO_AUTO_VALUE_ON_ZERO MUST be set before import
####################################
DROP DATABASE `ucm`;

CREATE DATABASE `ucm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ucm;

CREATE TABLE IF NOT EXISTS `summary` (
  `Street City` VARCHAR(100) NULL DEFAULT NULL,
  `Assigned Acct` VARCHAR(100) NULL DEFAULT NULL,
  `Assigned User ID` VARCHAR(100) NULL DEFAULT NULL,
  `Call Back` VARCHAR(100) NULL DEFAULT NULL,
  `City` VARCHAR(100) NULL DEFAULT NULL,
  `Client Ref` VARCHAR(100) NULL DEFAULT NULL,
  `Cmp Styl Info` VARCHAR(100) NULL DEFAULT NULL,
  `Company` VARCHAR(100) NULL DEFAULT NULL,
  `Completed` VARCHAR(100) NULL DEFAULT NULL,
  `Contact` VARCHAR(100) NULL DEFAULT NULL,
  `Contact Phone` VARCHAR(100) NULL DEFAULT NULL,
  `Contacted` VARCHAR(100) NULL DEFAULT NULL,
  `Country` VARCHAR(100) NULL DEFAULT NULL,
  `CUIC` VARCHAR(100) NULL DEFAULT NULL,
  `Cust IA` VARCHAR(100) NULL DEFAULT NULL,
  `Opened` VARCHAR(100) NULL DEFAULT NULL,
  `Updated` VARCHAR(100) NULL DEFAULT NULL,
  `Dept` VARCHAR(100) NULL DEFAULT NULL,
  `Device` VARCHAR(100) NULL DEFAULT NULL,
  `ET` VARCHAR(100) NULL DEFAULT NULL,
  `Headline` VARCHAR(100) NULL DEFAULT NULL,
  `Host Proc` VARCHAR(100) NULL DEFAULT NULL,
  `Incident` VARCHAR(100) NOT NULL,
  `Mfg` VARCHAR(100) NULL DEFAULT NULL,
  `Model` VARCHAR(100) NULL DEFAULT NULL,
  `Natl Global Acct` VARCHAR(100) NULL DEFAULT NULL,
  `Obligation` VARCHAR(100) NULL DEFAULT NULL,
  `Parts` VARCHAR(100) NULL DEFAULT NULL,
  `Phone Resp` VARCHAR(100) NULL DEFAULT NULL,
  `Postal Code` VARCHAR(100) NULL DEFAULT NULL,
  `Primary` VARCHAR(100) NULL DEFAULT NULL,
  `Pri` VARCHAR(100) NULL DEFAULT NULL,
  `Product` VARCHAR(100) NULL DEFAULT NULL,
  `Level` VARCHAR(100) NULL DEFAULT NULL,
  `Prov 1` VARCHAR(100) NULL DEFAULT NULL,
  `Prov 2` VARCHAR(100) NULL DEFAULT NULL,
  `Prov 3` VARCHAR(100) NULL DEFAULT NULL,
  `Prov 4` VARCHAR(100) NULL DEFAULT NULL,
  `Prov 5` VARCHAR(100) NULL DEFAULT NULL,
  `Prov Name` VARCHAR(100) NULL DEFAULT NULL,
  `Onsite D T` VARCHAR(100) NULL DEFAULT NULL,
  `Prov Pri` VARCHAR(100) NULL DEFAULT NULL,
  `Request Type` VARCHAR(100) NULL DEFAULT NULL,
  `Resolution Detail` VARCHAR(100) NULL DEFAULT NULL,
  `Resolution` VARCHAR(100) NULL DEFAULT NULL,
  `Res Type` VARCHAR(100) NULL DEFAULT NULL,
  `Response` VARCHAR(100) NULL DEFAULT NULL,
  `Restore` VARCHAR(100) NULL DEFAULT NULL,
  `SLA` VARCHAR(100) NULL DEFAULT NULL,
  `Scheduled` VARCHAR(100) NULL DEFAULT NULL,
  `Self ID` VARCHAR(100) NULL DEFAULT NULL,
  `SN` VARCHAR(100) NULL DEFAULT NULL,
  `Serv Tag` VARCHAR(100) NULL DEFAULT NULL,
  `Service Type` VARCHAR(100) NULL DEFAULT NULL,
  `St Pr` VARCHAR(100) NULL DEFAULT NULL,
  `Status` VARCHAR(100) NULL DEFAULT NULL,
  `UStyle` VARCHAR(100) NULL DEFAULT NULL,
  `SS` VARCHAR(100) NULL DEFAULT NULL,
  `Subacct 1` VARCHAR(100) NULL DEFAULT NULL,
  `Subacct 2` VARCHAR(100) NULL DEFAULT NULL,
  `Subacct 3` VARCHAR(100) NULL DEFAULT NULL,
  `Subacct 4` VARCHAR(100) NULL DEFAULT NULL,
  `Subacct 5` VARCHAR(100) NULL DEFAULT NULL,
  `Subacct 6` VARCHAR(100) NULL DEFAULT NULL,
  `SysDn` VARCHAR(100) NULL DEFAULT NULL,
  `TZ` VARCHAR(100) NULL DEFAULT NULL,
  `UnitDn` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Incident`),
  UNIQUE KEY `unique_index_incident`(`Incident`)
)
CHARACTER SET = utf8mb4,
COLLATE = utf8mb4_unicode_ci,
COMMENT = 'summary',
ENGINE = InnoDB
;

CREATE TABLE IF NOT EXISTS `pn`(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pn` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `provider` VARCHAR(100) NULL DEFAULT NULL,
  `category` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index_pn`(`pn`)
)
AUTO_INCREMENT=0,
CHARACTER SET = utf8mb4,
COLLATE = utf8mb4_unicode_ci,
COMMENT = 'pn',
ENGINE = InnoDB
;

CREATE TABLE IF NOT EXISTS `sn` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sn`  VARCHAR(100) NOT NULL,
  `pnid` INT(11) UNSIGNED NOT NULL,
  `company` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `primarycontact` VARCHAR(100) NULL DEFAULT NULL,
  `primarymail` VARCHAR(100) NULL DEFAULT NULL,
  `slavecontact` VARCHAR(100) NULL DEFAULT NULL,
  `slavemail` VARCHAR(100) NULL DEFAULT NULL,
  `ia` VARCHAR(100) NULL DEFAULT NULL,
  `party` VARCHAR(100) NULL DEFAULT NULL,
  `comment` TEXT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index_sn`(`sn`),
  FOREIGN KEY `foreign_key_pnid` (`pnid`) REFERENCES `pn` (`id`)
)
AUTO_INCREMENT=0,
CHARACTER SET = utf8mb4,
COLLATE = utf8mb4_unicode_ci,
COMMENT = 'sn',
ENGINE = InnoDB
;

CREATE TABLE IF NOT EXISTS `sr` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `srms`  VARCHAR(100) NOT NULL,
  `task` VARCHAR(100) NULL DEFAULT NULL,
  `sr` VARCHAR(100) NULL DEFAULT NULL,
  `snid` INT(11) UNSIGNED NOT NULL,
  `opendate` VARCHAR(100) NOT NULL,
  `headline` VARCHAR(255) NOT NULL,
  `notes` TEXT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index_srms`(`srms`),
  FOREIGN KEY `foreign_key_snid` (`snid`) REFERENCES `sn` (`id`)
#  FOREIGN KEY `foreign_key_srms` (`srms`) REFERENCES `summary` (`Incident`)
)
AUTO_INCREMENT=0,
CHARACTER SET = utf8mb4,
COLLATE = utf8mb4_unicode_ci,
COMMENT = 'sr',
ENGINE = InnoDB
;

CREATE TABLE IF NOT EXISTS `ac` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `srid` INT(11) UNSIGNED NOT NULL,
  `actiondate` VARCHAR(100) NOT NULL,
  `actiontime` VARCHAR(100) NOT NULL,
  `duration` VARCHAR(100) NOT NULL,
  `otfrom` VARCHAR(100) NULL DEFAULT NULL,
  `otto` VARCHAR(100) NULL DEFAULT NULL,
  `action` VARCHAR(100) NOT NULL,
  `actiontype` VARCHAR(100) NOT NULL,
  `remark` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY `foreign_key_srid` (`srid`) REFERENCES `sr` (`id`)
)
AUTO_INCREMENT=0,
CHARACTER SET = utf8mb4,
COLLATE = utf8mb4_unicode_ci,
COMMENT = 'ac',
ENGINE = InnoDB
;

CREATE TABLE IF NOT EXISTS `hw` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `acid` INT(11) UNSIGNED NOT NULL,
  `newpnid` INT(11) UNSIGNED NULL DEFAULT NULL,
  `newsn` VARCHAR(100) NULL DEFAULT NULL,
  `oldpnid` INT(11) UNSIGNED NULL DEFAULT NULL,
  `oldsn` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `newhw` (`newpnid`, `newsn`),
  INDEX `oldhw` (`oldpnid`, `oldsn`),
  FOREIGN KEY `foreign_key_acid` (`acid`) REFERENCES `ac` (`id`),
  FOREIGN KEY `foreign_key_newpnid` (`newpnid`) REFERENCES `pn` (`id`),
  FOREIGN KEY `foreign_key_oldpnid` (`oldpnid`) REFERENCES `pn` (`id`)
)
AUTO_INCREMENT=0,
CHARACTER SET = utf8mb4,
COLLATE = utf8mb4_unicode_ci,
COMMENT = 'hw',
ENGINE = InnoDB
;
